# Generated by Django 4.2.28 on 2026-03-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_solarcoolbox_alter_user_role'),
        ('marketplace', '0003_user_otp_fields'),
    ]

    operations = [
    ]
