# Generated by Django 4.2.28 on 2026-03-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_coolboxrental_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolboxrental',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=20),
        ),
    ]
