# Generated by Django 4.2.28 on 2026-03-31 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_coolboxrental_status'),
        ('marketplace', '0007_coolboxrental_quantity_kg_amount_per_day'),
    ]

    operations = [
    ]
