# Generated by Django 4.2.28 on 2026-04-01 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_remove_user_otp_fields'),
        ('marketplace', '0008_merge_20260331_1954'),
    ]

    operations = [
    ]
